<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <artifactId>bixi-module</artifactId>
        <groupId>com.lotus</groupId>
        <version>${revision}</version>
    </parent>

    <artifactId>bixi-workflow-api</artifactId>
    <packaging>jar</packaging>
    <description>bixi 工作流接口契约模块</description>

    <dependencies>
        <dependency>
            <groupId>com.lotus</groupId>
            <artifactId>bixi-common-core</artifactId>
        </dependency>
        <dependency>
            <groupId>com.lotus</groupId>
            <artifactId>bixi-common-feign</artifactId>
        </dependency>
        <dependency>
            <groupId>com.lotus</groupId>
            <artifactId>bixi-common-mybatis</artifactId>
        </dependency>
    </dependencies>
</project>
