spring:
  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
      database: ${REDIS_DATABASE:0}
  rabbitmq:
    host: ${RABBITMQ_HOST:127.0.0.1}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST:/}
  boot:
    admin:
      client:
        enabled: false
  main:
    allow-bean-definition-overriding: true

bixi:
  reliable:
    enabled: ${BIXI_RELIABLE_ENABLED:false}
    rabbit:
      enabled: ${BIXI_RELIABLE_RABBIT_ENABLED:false}
      host: ${BIXI_RELIABLE_RABBIT_HOST:${RABBITMQ_HOST:127.0.0.1}}
      port: ${BIXI_RELIABLE_RABBIT_PORT:${RABBITMQ_PORT:5672}}
      username: ${BIXI_RELIABLE_RABBIT_USERNAME:${RABBITMQ_USERNAME:}}
      password: ${BIXI_RELIABLE_RABBIT_PASSWORD:${RABBITMQ_PASSWORD:}}
      virtual-host: ${BIXI_RELIABLE_RABBIT_VIRTUAL_HOST:${RABBITMQ_VIRTUAL_HOST:/}}

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,dynamictp

logging:
  level:
    root: INFO
    com.lotus.bixi: INFO
