spring:
  freemarker:
    suffix: .ftl
    template-loader-path: classpath:/templates/
    request-context-attribute: request
management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
  endpoints:
    web:
      exposure:
        include: health

security:
  micro: true
  encode-key: ${BIXI_ENCODE_KEY}
  ignore-clients:
    - bixi
    - test
  oauth2:
    ignore:
      urls:
        - /token/**
        - /code/**
        - /actuator/health
        - /actuator/health/**
        - /error

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
