package com.lotus.bixi.workflow.api.event;

public enum WorkflowEventType {
    WORKFLOW_START_REQUESTED,
    WORKFLOW_STARTED,
    WORKFLOW_START_REJECTED,
    WORKFLOW_COMPLETED,
    WORKFLOW_BUSINESS_TASK_REQUESTED,
    WORKFLOW_BUSINESS_TASK_RESULT,
    WORKFLOW_COMPENSATION_REQUESTED,
    WORKFLOW_COMPENSATION_RESULT
}
