server:
  port: 5008

spring:
  application:
    name: @artifactId@
  cloud:
    nacos:
      username: ${NACOS_USERNAME:}
      password: ${NACOS_PASSWORD:}
      discovery:
        server-addr: ${NACOS_HOST:127.0.0.1}:${NACOS_PORT:8848}
        namespace: ${NACOS_NAMESPACE:@nacos.namespace@}
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        namespace: ${NACOS_NAMESPACE:@nacos.namespace@}
  config:
    import:
      - nacos:application-@profiles.active@.yml
      - nacos:${spring.application.name}-@profiles.active@.yml
      - optional:nacos:${spring.application.name}-dtp-@profiles.active@.yml

bixi:
  deployment:
    mode: cloud
  reliable:
    enabled: ${BIXI_RELIABLE_ENABLED:false}
    rabbit:
      enabled: ${BIXI_RELIABLE_RABBIT_ENABLED:false}

workflow:
  enabled: ${WORKFLOW_ENABLED:false}
  database-schema-update: ${WORKFLOW_SCHEMA_UPDATE:false}
  async-executor-activate: ${WORKFLOW_ASYNC_EXECUTOR_ACTIVATE:true}
  history-level: full

flowable:
  check-process-definitions: false
